#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-rabbitmq
Version  : 4.2.0
Release  : 1
URL      : https://repo1.maven.org/maven2/com/rabbitmq/amqp-client/4.2.0/amqp-client-4.2.0-sources.jar
Source0  : https://repo1.maven.org/maven2/com/rabbitmq/amqp-client/4.2.0/amqp-client-4.2.0-sources.jar
Source1  : https://repo1.maven.org/maven2/com/rabbitmq/amqp-client/4.2.0/amqp-client-4.2.0.jar
Source2  : https://repo1.maven.org/maven2/com/rabbitmq/amqp-client/4.2.0/amqp-client-4.2.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause GPL-2.0 HPND MIT MPL-1.1 MPL-2.0 MPL-2.0-no-copyleft-exception
Requires: mvn-rabbitmq-data = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
No detailed description available

%package data
Summary: data components for the mvn-rabbitmq package.
Group: Data

%description data
data components for the mvn-rabbitmq package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/rabbitmq/amqp-client/4.2.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/rabbitmq/amqp-client/4.2.0/amqp-client-4.2.0-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/rabbitmq/amqp-client/4.2.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/rabbitmq/amqp-client/4.2.0/amqp-client-4.2.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/rabbitmq/amqp-client/4.2.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/rabbitmq/amqp-client/4.2.0/amqp-client-4.2.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/rabbitmq/amqp-client/4.2.0/amqp-client-4.2.0-sources.jar
/usr/share/java/.m2/repository/com/rabbitmq/amqp-client/4.2.0/amqp-client-4.2.0.jar
/usr/share/java/.m2/repository/com/rabbitmq/amqp-client/4.2.0/amqp-client-4.2.0.pom
